# Generated by Django 4.1.3 on 2022-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_status', models.CharField(max_length=100)),
                ('consultation', models.CharField(max_length=100)),
                ('discharged', models.BooleanField()),
                ('admitted', models.DateField()),
                ('referred', models.CharField(max_length=100)),
            ],
        ),
    ]
