# Generated by Django 4.1.3 on 2022-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='consultation',
            new_name='hospital',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='discharged',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='patient_status',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='referred',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='medication',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='patient_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='admitted',
            field=models.BooleanField(),
        ),
    ]
