# Generated by Django 4.1.3 on 2022-11-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_consultation_patientinfo_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bedsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalBeds', models.IntegerField(default=0)),
                ('CovidBeds', models.IntegerField(default=0)),
                ('RegularBeds', models.IntegerField(default=0)),
                ('hospital_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo')),
            ],
        ),
    ]
