# Generated by Django 4.1.3 on 2022-11-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_bedsinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='hospital',
            new_name='hospital_name',
        ),
    ]
