# Generated by Django 4.1.3 on 2022-11-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_hospital_patientinfo_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsinfo',
            name='hospital_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='hospital_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.bedsinfo'),
        ),
    ]
