# Generated by Django 4.1.3 on 2022-11-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_bedsinfo_hospital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsinfo',
            name='hospital_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientinfo'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='hospital_name',
            field=models.CharField(max_length=100),
        ),
    ]
