# Generated by Django 4.1.3 on 2022-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_bedsinfo_hospital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsinfo',
            name='hospital_name',
            field=models.CharField(max_length=50),
        ),
    ]
