# Generated by Django 4.1.3 on 2022-11-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_bedsinfo_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='patient_id',
        ),
    ]
