# Generated by Django 4.1.3 on 2022-11-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='consultation',
            new_name='beds_available',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='disease',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='doctor_name',
            new_name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='admitted',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='discharged',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='patient_status',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='referred',
        ),
    ]
