# Generated by Django 4.1.3 on 2022-11-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_rename_consultation_hospital_beds_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='covid_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='regular_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beds_available',
            field=models.IntegerField(),
        ),
    ]
